codingtest-study2024/codingtest-java-study

- jiwon-woo/Day6
Reverts codingtest-study2024/codingtest-java-study#19
> Revert "jiwonniy / 0328 / 4문제"

- dayeon-lee/Day6
> dylee00 / 0328 / 4문제

- dayeon-lee/Day7
> dylee00 / 0329 / 4문제

- Day7
> sonyerim / 0329 / 4문제

- Day8
> sonyerim / 0330 / 4문제

- dayeon-lee/Day8
> dylee00 / 0330 / 4문제

- dayeon-lee/Day9
> dylee00 / 0331 / 4문제

- sonyerim/Day10
> sonyerim / 0401 / 4문제

- sonyerim/Day11
> sonyerim / 0403 / 4문제

- yoojin-kim/Week3/Day11.java
최댓값 만들기(1) 에서 원래 풀고 싶은 방법이 있었는데 테스트 통과에 실패해서 다른 알고리즘으로 풀었음.
> ouob123 / 0403 / 4 문제

- dayeon-lee/Day12
> dylee00 / 0404 / 4문제

- dayeon-lee/Day13
> dylee00 / 0405 / 4문제

- dayeon-lee/Day14
> dylee00 / 0406 / 4문제

- sonyerim/Day15
> sonyerim / 0407 / 4문제

- dayeon-lee/Day15
> dylee00 / 0407 / 4문제

- eunchae-cho/week3/Day14/120890. 가까운 수 /가까운 수.java
- eunchae-cho/week3/Day14/120891. 369게임 /369게임.java
- eunchae-cho/week3/Day14/120892. 암호 해독 /암호 해독.java
- eunchae-cho/week3/Day14/120893. 대문자와 소문자 /대문자와 소문자.java
- eunchae-cho/week3/Day15/120894. 영어가 싫어요 /영어가 싫어요.java
- eunchae-cho/week3/Day15/120895. 인덱스 바꾸기 /인덱스 바꾸기.java
- eunchae-cho/week3/Day15/120896. 한 번만 등장한 문자 /한 번만 등장한 문자.java
- eunchae-cho/week3/Day15/120897. 약수 구하기 /약수 구하기.java
> givesilverstick / 240407 / 8문제

- dayeon-lee/Day16
> dylee00 / 0408 / 4문제

- sonyerim/Day16
> sonyerim / 0408 / 4문제

- eunchae-cho/week3/Day16/120898. 편지 /README.md
- eunchae-cho/week3/Day16/120898. 편지 /편지.java
- eunchae-cho/week3/Day16/120899. 가장 큰 수 찾기 /README.md
- eunchae-cho/week3/Day16/120899. 가장 큰 수 찾기 /가장 큰 수 찾기.java
- eunchae-cho/week3/Day16/120902. 문자열 계산하기 /문자열 계산하기.java
- eunchae-cho/week3/Day16/120903. 배열의 유사도 /배열의 유사도.java
> givesilverstick / 240408 / 4문제

- jiwon-woo/Day17.java
> jiwonniy / 0501 / 4문제

- sonyerim/Day17
> sonyerim / 0501 / 4문제

- jiwon-woo/Day18.java
> jiwonniy / 0502 / 4문제

- sonyerim/Day18
> [PGS] Day18 / 문자열안에 문자열, 제곱수 판별하기, 세균 증식, 문자열 정렬하기 (2)

- yoojin-kim/Week4/Day18.java
- match 변수: true로 초기화
- 내부 반복문에서 `str1`과 `str2`의 각 문자를 비교하여 일치하는 경우 내부 반복문 종료 후 1 반환
- 내부 반복문에서 `str1`과 `str2`의 각 문자를 비교하여 일치하지 않는 경우 match를 false로 설정하고 2 반환
**📌Math.pow**
- 자바의 Math 클래스에 있는 메소드
- 두 개의 인자를 받아 첫 번째 인자를 밑으로 하고 두 번째 인자를 지수로 하는 거듭제곱 값을 계산
**📌 문자열을 알파벳 순서로 정렬**
- 문자열을 문자 배열로 변환 → 배열 정렬 → 정렬된 배열을 다시 문자열로 변환
> ouob123 / 0502 / 4 문제

- jiwon-woo/Day19.java
> jiwonniy / 0503 / 4문제

- sonyerim/Day19
아이디 / 날짜 / 몇 문제
늦어서 죄송합니다..........
> sonyerim / 0503 / 4문제

- yoojin-kim/Week4/Day20.java
**📌Math.abs**
- Math.abs 메소드는 자바에서 절대값을 구하는 데 사용
**📌나중에 다시 풀어보기**
**📌초기 최댓값 설정**
- 배열 원소들의 곱을 비교해서 최댓값으로 갱신하기 위해서는 매우 작은 값을 초기 최댓값으로 설정해야 함.
**📌나중에 다시 풀어보기**
- 도저히 모르겠어서 베스트 코드 참고, 나중에 꼭 다시 풀어봐야 함.
> ouob123 / 0504 / 4 문제

- sonyerim/Day20
> sonyerim / 0504 / 4문제

- jiwon-woo/Day20.java
> jiwonniy / 0504 / 4문제

- jiwon-woo/Day21.java
> jiwonniy / 0505 / 4문제

- jiwon-woo/Day22.java
> jiwonniy / 0506 / 4문제

- yoojin-kim/Week4/Day21.java
- 중간부터 다시 풀어보기
**📌 나중에 다시 풀어보기**
- 다른 사람의 풀이를 참조한 문항
📌 **전체 로직**
- 지뢰가 있는 위치를 찾아 그 주변을 위험 지역으로 표시한 후, 전체 보드에서 안전한 영역(지뢰도 위험 지역도 아닌)의 개수를 세어 반환
1️⃣ &nbsp;지뢰 위치 찾기: 
- 주어진 board 배열을 순회하면서 지뢰(1로 표시된 위치)를 찾음. 
- 지뢰를 찾을 때마다 danger 함수를 호출하여 해당 지뢰의 주변 영역을 위험 지역으로 표시함.
2️⃣ &nbsp;위험 지역 표시: 
- danger 함수는 지뢰의 위치(i, j)를 받아서 해당 위치를 포함하여 주변 8칸을 모두 위험 지역으로 표시
- 즉, 해당 칸과 상하좌우, 그리고 대각선 방향의 칸들을 모두 1로 표시
- 여기서 배열의 경계를 넘어가지 않도록 조건 확인
3️⃣ &nbsp;안전한 영역 세기: 
- countDanger 함수는 위에서 새로 표시한 newBoard 배열을 순회하면서 안전한 영역의 개수를 세어 반환
- 특이사항 없음.
**📌 나중에 다시 풀어보기**
- 다른 사람의 풀이를 참조한 문항
> ouob123 / 0505 / 4 문제

- sonyerim/Day21
- sonyerim/Day22
> sonyerim / 0505~0506 / 8문제

- jiwon-woo/Week7/Day23.java
> jiwonniy / 0508 / 4문제

- jiwon-woo/Week7/Day24.java
> jiwonniy / 0509 / 4문제

- dayeon-lee/Day23
> dylee00 /0509/4문제

- jiwon-woo/Week7/Day25.java
> jiwonniy / 0510 / 4문제

- sonyerim/Day23
- sonyerim/Day24
- sonyerim/Day25
> sonyerim / 0508~0510 / 12문제

- yoojin-kim/Week5/Day23.java
**📌나중에 다시 풀어보기**
- 다른 사람의 풀이를 참조한 문항
<br>
**📌나중에 다시 풀어보기**
- 다른 사람의 풀이를 참조한 문항
**📌나중에 다시 풀어보기**
- 다른 사람의 풀이를 참조한 문항
> ouob123 / 0508 / 4 문제

- dayeon-lee/Lecture/4강~6강 정리
> Create 4강~6강 정리
